AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for server project

Resources:
  ServerRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageTagMutability: IMMUTABLE

Outputs:
  ECR_REPOSITORY:
    Description: The ECR repository ARN
    Value: !Ref ServerRepository
