AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for server project

Resources:
  ServerRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageTagMutability: IMMUTABLE

Outputs:
  ECRRepositoryUri:
    Description: The ECR repository URI
    Value: !GetAtt [ServerRepository, RepositoryUri]
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepositoryUri"

  ECRRepositoryName:
    Description: The ECR repository name
    Value: !Ref ServerRepository
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepositoryName"
