name: Deploy to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  AWS_STACK_NAME: patapon

permissions:
  contents: read

jobs:
  deploy_code:
    name: Deploy Code
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get resource arns
        id: get-arns
        run: |
          STACK_OUTPUT=$(
            aws cloudformation describe-stacks \
              --region ${{ env.AWS_REGION }} \
              --stack-name ${{ env.AWS_STACK_NAME }} \
              --query 'Stacks[0].Outputs[*].[OutputKey,OutputValue]' \
              --no-paginate \
              --output text
          )

          while IFS= read -r line
          do
            read -r key value <<< $line
            echo "::set-output name=$key::$value"
          done <<< "$STACK_OUTPUT"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REPOSITORY: ${{ steps.get-arns.outputs.RepositoryName }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

          # Build a docker container and push it to ECR
          docker build . --file image-lambda.Dockerfile --tag $IMAGE_URI
          docker push $IMAGE_URI

          # Output the new image URI
          echo "::set-output name=image::$IMAGE_URI"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Get environment variables for image
        id: get-env-vars
        env:
          ENVIRONMENT_NAME: ${{ steps.get-arns.outputs.EnvironmentName }}
        run: |
          SSM_OUTPUT=$(
            aws ssm get-parameters-by-path \
              --path /${{ env.AWS_STACK_NAME }}/$ENVIRONMENT_NAME \
              --no-paginate \
              --query "Parameters[*].{Name:Name,Value:Value}" \
              --with-decryption \
              --output text \
          )

          echo "OUTPUT:: $SSM_OUTPUT"

          ENVIRONMENT_VARIABLES=()
          while IFS= read -r line
          do
            read -r PARAM_PATH PARAM_VALUE <<< $line
            PARAM_KEY="${PARAM_PATH##*/}"
            ENVIRONMENT_VARIABLES+=($PARAM_KEY=$PARAM_VALUE)
          done <<< "$SSM_OUTPUT"

          echo "ENVARS:: $ENVIRONMENT_VARIABLES"

          printf -v ENVIRONMENT_VARIABLES_STR '%s,' "${data[@]}"
          ENVIRONMENT_VARIABLES_STR="${ENVIRONMENT_VARIABLES_STR%,}"
          echo "::set-output name=ENVIRONMENT_VARIABLES_STR::$ENVIRONMENT_VARIABLES_STR"
          echo "LISTO:: $ENVIRONMENT_VARIABLES_STR"

      - name: Create and deploy a Lambda function
        id: lambda-function
        env:
          LAMBDA_EXECUTION_ROLE: ${{ steps.get-arns.outputs.LambdaExecutionRoleArn }}
          ENVIRONMENT_VARIABLES: ${{ steps.get-env-vars.outputs.ENVIRONMENT_VARIABLES_STR }}

        run: |
          LAMBDA_ARN=$(
            aws lambda create-function \
              --function-name $IMAGE_TAG \
              --code ImageUri=$IMAGE_URI \
              --role $LAMBDA_EXECUTION_ROLE \
              --package-type Image \
              --environment Variables="{$ENVIRONMENT_VARIABLES}" \
              --output text \
              --query 'FunctionArn' \
              --publish
          )

          aws lambda wait function-active-v2 --function-name $LAMBDA_ARN

          echo "::set-output name=LAMBDA_ARN::$LAMBDA_ARN"
          echo "LAMBDA_ARN=$LAMBDA_ARN" >> $GITHUB_ENV

          aws lambda add-permission \
            --function-name $LAMBDA_ARN \
            --action lambda:InvokeFunction \
            --principal elasticloadbalancing.amazonaws.com \
            --statement-id $IMAGE_TAG

      - name: Deregister old Lambda function from Target Group
        id: deregister-old-lambda-function
        env:
          TARGET_GROUP_ARN: ${{ steps.get-arns.outputs.TargetGroupArn }}
        run: |
          OLD_LAMBDA_ARN=$(
            aws elbv2 describe-target-health \
            --target-group-arn $TARGET_GROUP_ARN \
            --query 'TargetHealthDescriptions[0].Target.Id' \
            --output text
          )

          echo "OLD_LAMBDA_ARN=$OLD_LAMBDA_ARN" >> $GITHUB_ENV

          if [ "$OLD_LAMBDA_ARN" != "None" ]; then
            aws elbv2 deregister-targets \
              --target-group-arn $TARGET_GROUP_ARN \
              --targets Id=$OLD_LAMBDA_ARN
          fi

      - name: Register the new Lambda function with the Target Group
        id: register-lambda-function
        env:
          TARGET_GROUP_ARN: ${{ steps.get-arns.outputs.TargetGroupArn }}
        run: |
          aws elbv2 register-targets \
            --target-group-arn $TARGET_GROUP_ARN \
            --targets Id=$LAMBDA_ARN

      - name: Delete old Lambda function
        id: delete-old-lambda-function
        if: ${{ env.OLD_LAMBDA_ARN != 'None' }}
        run: |
          aws lambda delete-function --function-name $OLD_LAMBDA_ARN
